spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance-account?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 3000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.finance.account.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
